name: sistempemuda2
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistempemuda2_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - npm_network
      - mariadb_network
      - sistempemuda_network
    user: root
  nginx:
    image: nginx:alpine
    container_name: sistempemuda2_nginx
    restart: unless-stopped
    ports:
      - "85:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - npm_network
      - sistempemuda_network
networks:
  npm_network:
    external: true
  mariadb_network:
    external: true
  sistempemuda_network:
    driver: bridge
