version: "3"
services:
  app:
    image: itjprp108/sistempemuda:latest
    container_name: sistempemuda-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./.env.prod:/var/www/.env
      - app-volume:/var/www
    networks:
      - npm_network
      - mariadb_network
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: sistempemuda-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app-volume:/var/www
    networks:
      - npm_network
    expose:
      - "80"
    depends_on:
      - app

volumes:
  app-volume:
    driver: local

networks:
  npm_network:
    external: true
  mariadb_network:
    external: true
